#spring:
#  application:
#    name: spring-taco-cloud
#  datasource:
#    generate-unique-name: false
#    name: tacocloud
spring:
  mongodb:
    uri: mongodb://localhost:27017/tacocloud
    database: tacocloud
    username: tacocloud