#spring:
#  application:
#    name: spring-taco-cloud
#  datasource:
#    generate-unique-name: false
#    name: tacocloud
spring:
    cassandra:
        keyspace-name: taco_cloud
        schema-action: recreate
        local-datacenter: datacenter1